apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: nandanholla/frontend-app:1.1
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
        - containerPort: 4200
